export const ADMIN_PERMISSIONS = {
    ALL_ACCESS: "ALL_ACCESS",

  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  // Payments
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  VIEW_PAYMENT_DETAILS:
    "VIEW_PAYMENT_DETAILS",
  CREATE_PAYMENT: "CREATE_PAYMENT",

  // Admins
  VIEW_ADMINS: "VIEW_ADMINS",
  CREATE_SUB_ADMIN: "CREATE_SUB_ADMIN",
  EDIT_SUB_ADMIN: "EDIT_SUB_ADMIN",
  RESET_SUB_ADMIN_PASSWORD:
    "RESET_SUB_ADMIN_PASSWORD",

  EDIT_SUPER_ADMIN:
    "EDIT_SUPER_ADMIN",

  RESET_SUPER_ADMIN_PASSWORD:
    "RESET_SUPER_ADMIN_PASSWORD",

  // Vendors
  VIEW_VENDORS: "VIEW_VENDORS",
  CREATE_VENDOR: "CREATE_VENDOR",
  EDIT_VENDOR: "EDIT_VENDOR",
  ACTIVATE_VENDOR: "ACTIVATE_VENDOR",
  DEACTIVATE_VENDOR:
    "DEACTIVATE_VENDOR",
  DELETE_VENDOR: "DELETE_VENDOR",

  VIEW_VENDOR_PAYMENTS:
    "VIEW_VENDOR_PAYMENTS",
};